### ISSUE TITLE
deepmosaic-draw: error: unrecognized arguments: -db gnomad_genome

### ISSUE THREAD

**Issue by gevro** [shishenyxx/DeepMosaic#21]
Hi,
I'm getting this error:
```
usage: deepmosaic-draw [-h] -i INPUT_FILE [-f VCF_FILTERS] -o OUTPUT_DIR -a
                       ANNOVAR_PATH [-b BUILD]
deepmosaic-draw: error: unrecognized arguments: -db gnomad_genome
```

It looks like deepmosaic-draw does not have the -db option even though the documentation says it does.

I am using the singularity version of deepmosaic.

**Comment by gevro** [comment]
I think your singularity image is out of date? Can you please update it? Then I can download the new version.
Thanks

**Comment by shishenyxx** [comment]
> Hi, I'm getting this error:
> 
> ```
> usage: deepmosaic-draw [-h] -i INPUT_FILE [-f VCF_FILTERS] -o OUTPUT_DIR -a
>                        ANNOVAR_PATH [-b BUILD]
> deepmosaic-draw: error: unrecognized arguments: -db gnomad_genome
> ```
> 
> It looks like deepmosaic-draw does not have the -db option even though the documentation says it does.
> 
> I am using the singularity version of deepmosaic.

Looking into this and will get back to you shortly, alternatively, you can download it directly with git-lfs.

**Comment by gevro** [comment]
Thanks. What is the command exactly to download the latest singularity image with git LFS?

**Comment by gevro** [comment]
I also tried this: git clone --recursive https://github.com/Virginiaxu/DeepMosaic

But it downloads only 191M instead of 4Gb as the documentation says. So I think best would be if you all can update the singularity image to the latest code.

**Comment by shishenyxx** [comment]
> I also tried this: git clone --recursive https://github.com/Virginiaxu/DeepMosaic
> 
> But it downloads only 191M instead of 4Gb as the documentation says. So I think best would be if you all can update the singularity image to the latest code.

![image](https://github.com/shishenyxx/DeepMosaic/assets/17311837/29914f5a-e8bd-4dd5-ab5f-82fc823cee49)
That's what I meant in the previous post. If you install git-lfs following the screenshot in the tutorial you would be able to download the >4G package from this GitHub repository. We are downloading the singularity you previously reported.

**Comment by arzoopatel5** [comment]
![image](https://github.com/shishenyxx/DeepMosaic/assets/84895315/080f247c-a01a-485a-9d2b-9d3f1dfd0514)
I've re-downloaded the singularity container from [sylabs](https://cloud.sylabs.io/library/arzoopatel5/deepmosaic/deepmosaic) using the command `singularity pull --arch amd64 library://arzoopatel5/deepmosaic/deepmosaic:v1.1.1`. `-db` is included in this version. Please check that you're using the most recent singularity container (`v1.1.1`) that was uploaded on Aug 4th. If the Issue persists, please provide us with the input command so we can continue debugging.

**Comment by gevro** [comment]
Thank you. I downloaded the image before Aug 4 so that must be why the -db option was missing. I will download the new version! Really appreciate your rapid response.
