### ISSUE TITLE
Multi-threaded support

### ISSUE THREAD

**Issue by gevro** [shishenyxx/DeepMosaic#24]
Hi,
Do either of the deepmosaic steps support multi-threading to help speed up the pipeline?
Thanks

**Comment by shishenyxx** [comment]
To significantly speed up the pipeline

1. You can try to run it on GPU nodes.
2. You can try to split the input, refer to issue #7 and issue #8 

Best,

Xiaoxu

**Comment by gevro** [comment]
Ok thank you.
