### ISSUE TITLE
Large number of output files

### ISSUE THREAD

**Issue by gevro** [shishenyxx/DeepMosaic#28]
Hi, There seems to be an output folder with a huge number of files. So many that it takes a long time to delete. Which directory is this, and is this a necessary output and/or is there a way to suppress this?
Thanks!

**Comment by shishenyxx** [comment]
Hi gevro,

`${output_folder}/images` contains all the images generated for your run (one image per variant) and `${output_folder}/matrices` contains all the matrices generated from the images, also one per variant. The images are the official output of your variant to visualize it if you want to make the case for your selected variants. The matrixes are required input for the classifier. The path to each of the variants is listed in the final output file. If you limit the number of your initial input variants you can limit this output.

Best,

Xiaoxu

**Comment by gevro** [comment]
Thanks

**Comment by shishenyxx** [comment]
You can use `tar -cvf files.tar ${my_directory} --remove-files` to compress the folder into one single tar and delete it, not sure it will take less time than you directly delete them with `rm` though.
