### ISSUE TITLE
How to run DeepMosaic with nanopore WGS data?

### ISSUE THREAD

**Issue by ymcki** [shishenyxx/DeepMosaic#29]
I presume bams cannot be prepped with GATK3 pipeline. 

Does feeding bam/cram from the wf-alignment pipeline work?
https://github.com/epi2me-labs/wf-alignment

**Comment by shishenyxx** [comment]
Hi ymcki,

Are these nanopore long read or short reads? The plotting area is currently +- 150 bp of the variant spot, making it hard to directly use it for long read sequencing. 

If these are short reads GATK3 processed bams with indel realign and BQSR could be used as input. Currently we are not taking crams.

If they are long read and you have some variants you want to use as positive and negative control you can try to use the training codes to try to train a new model. The plotting area should be changed accordingly.

Best,

Xiaoxu

**Comment by ymcki** [comment]
They are R10.4.1 long reads. Currently mainstream long read variant callers (e.g. DeepVariant, clair3) doesn't support mosaicism or high ploidy mode. If your software can also work on long read, I think it can fill a big hole in that area.

**Comment by shishenyxx** [comment]
> They are R10.4.1 long reads. Currently mainstream long read variant callers (e.g. DeepVariant, clair3) doesn't support mosaicism or high ploidy mode. If your software can also work on long read, I think it can fill a big hole in that area.

Yeah, we are definitely working towards it.
