### ISSUE TITLE
Indel predictions

### ISSUE THREAD

**Issue by rickyfg** [shishenyxx/DeepMosaic#31]
Hi, 
I'm testing Deepmosaic on a true positive and I have noticed that the predictions.txt file does not contain the true positive variant because it is a Indel. Predictions.txt does not contain any Indel that is present in the input vcf file and I tried also to recalculate Indel qualities in the BAM file with Dindel but it seems that this tool can handle only SNVs. Can you confirm this?

Best Regards,

Riccardo

**Comment by shishenyxx** [comment]
Hi Riccardo,

Thank you for the question, the current version of DeepMosaic only supports SNVs.

Best,

Xiaoxu
