### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by BenpengMiao** [shishenyxx/DeepMosaic#36]
Hi,

Will you develop the docker image of DeepMosaic?

**Comment by shishenyxx** [comment]
> Hi,
> 
> Will you develop the docker image of DeepMosaic?

Hi,

To convert the current singularity image to docker you can follow this: 

[https://stackoverflow.com/questions/60451712/how-to-build-docker-image-from-singularity-image](https://stackoverflow.com/questions/60451712/how-to-build-docker-image-from-singularity-image)

In future releases, we can try to first make a docker image and provide codes to help convert to singularity.

Best,,

Xiaoxu
