### ISSUE TITLE
NAs in the predictions

### ISSUE THREAD

**Issue by msherafatian** [shishenyxx/DeepMosaic#37]
We have used this algorithm on deep exome data but there seems to be a lot of NAs in our predictions. Nearly half of the predictions are NAs. What could be the reason for it?

**Comment by shishenyxx** [comment]
> We have used this algorithm on deep exome data but there seems to be a lot of NAs in our predictions. Nearly half of the predictions are NAs. What could be the reason for it?

Hi Masih,

Would you please confirm that only the prediction result is NA and that other columns are outputting correctly? Did you use the singularity version? Does the demo input work for you? 

If you are using the correct genome and annotation versions (same as your vcf coordinate), then I assume it is either you have low-quality calls (such as lots of Ns in the bam) or some of the annotations/feature extractions are not matching.

Best,

Xiaoxu
