### ISSUE TITLE
deepmosaic-draw : Not Recognizing Valid Input File

### ISSUE THREAD

**Issue by rlaskar** [shishenyxx/DeepMosaic#39]
I am encountering an issue where deepmosaic-draw is not recognizing a valid input file. The command I am running is as follows:

singularity exec -B variant_calling/software/annovar/annovar:/mnt/annovar /singularity/deepmosaic_v1.1.1.img deepmosaic-draw -i /variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /mnt/annovar -b hg38 -db gnomad_genome

**I have a valid input.txt file in the following format (using demo files):**
#sample_name    bam     vcf     depth   sex
sample_1    /variant_calling/software/annovar/demo/bams/sample_1.bam    /variant_calling/software/annovar/demo/vcfs/sample_1.vcf    200 M
sample_2    /variant_calling/software/annovar/demo/bams/sample_2.bam    /variant_calling/software/annovar/demo/vcfs/sample_2.vcf    200 M
sample_3    /variant_calling/software/annovar/demo/bams/sample_3.bam    /variant_calling/software/annovar/demo/vcfs/sample_3.vcf    200 M
sample_4    /variant_calling/software/annovar/demo/bams/sample_4.bam    /variant_calling/software/annovar/demo/vcfs/sample_4.vcf    200 M

**I receive the following error:**
Please provide a valid input file.

**Comment by shishenyxx** [comment]
> I am encountering an issue where deepmosaic-draw is not recognizing a valid input file. The command I am running is as follows:
> 
> singularity exec -B variant_calling/software/annovar/annovar:/mnt/annovar /singularity/deepmosaic_v1.1.1.img deepmosaic-draw -i /variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /mnt/annovar -b hg38 -db gnomad_genome
> 
> **I have a valid input.txt file in the following format (using demo files):** #sample_name bam vcf depth sex sample_1 /variant_calling/software/annovar/demo/bams/sample_1.bam /variant_calling/software/annovar/demo/vcfs/sample_1.vcf 200 M sample_2 /variant_calling/software/annovar/demo/bams/sample_2.bam /variant_calling/software/annovar/demo/vcfs/sample_2.vcf 200 M sample_3 /variant_calling/software/annovar/demo/bams/sample_3.bam /variant_calling/software/annovar/demo/vcfs/sample_3.vcf 200 M sample_4 /variant_calling/software/annovar/demo/bams/sample_4.bam /variant_calling/software/annovar/demo/vcfs/sample_4.vcf 200 M
> 
> **I receive the following error:** Please provide a valid input file.

Hi Rezwanuzzaman, have you tried to use singularity on the sif as indicated in the tutorial?

**Comment by Rezwanuzzaman** [comment]
Yes, I do. But same error::
Please provide a valid input file.

Command::
singularity exec -B variant_calling/software/annovar/annovar:/mnt/annovar /singularity/deepmosaic_v1.1.1.sif  deepmosaic-draw -i /variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /mnt/annovar -b hg38 -db gnomad_genome

**Comment by shishenyxx** [comment]
> Yes, I do. But same error:: **Please provide a valid input file.**
> 
> Command:: _singularity exec -B variant_calling/software/annovar/annovar:/mnt/annovar /singularity/deepmosaic_v1.1.1.sif deepmosaic-draw -i /variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /mnt/annovar -b hg38 -db gnomad_genome_
> 
> In another instance, when I use exactly the same command as described in the tutorial, it shows another error -
> 
> **Please provide a valid annovar program directory.**
> 
> The command is-
> 
> _singularity exec deepmosaic_v1.1.1.sif deepmosaic-draw -i variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /variant_calling/software/annovar/annovar -b hg38 -db gnomad_genome_

Hi Rezwanuzzaman, did you check if the input file is tab delineated?

**Comment by Rezwanuzzaman** [comment]
> > Yes, I do. But same error:: **Please provide a valid input file.**
> > Command:: _singularity exec -B variant_calling/software/annovar/annovar:/mnt/annovar /singularity/deepmosaic_v1.1.1.sif deepmosaic-draw -i /variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /mnt/annovar -b hg38 -db gnomad_genome_
> > In another instance, when I use exactly the same command as described in the tutorial, it shows another error -
> > **Please provide a valid annovar program directory.**
> > The command is-
> > _singularity exec deepmosaic_v1.1.1.sif deepmosaic-draw -i variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /variant_calling/software/annovar/annovar -b hg38 -db gnomad_genome_
> 
> **Hi Rezwanuzzaman, did you check if the input file is tab delineated?**

Yes, I use tab delineated input file but the error is same 'Please provide a valid input file.'

**Comment by shishenyxx** [comment]
> > > Yes, I do. But same error:: **Please provide a valid input file.**
> > > Command:: _singularity exec -B variant_calling/software/annovar/annovar:/mnt/annovar /singularity/deepmosaic_v1.1.1.sif deepmosaic-draw -i /variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /mnt/annovar -b hg38 -db gnomad_genome_
> > > In another instance, when I use exactly the same command as described in the tutorial, it shows another error -
> > > **Please provide a valid annovar program directory.**
> > > The command is-
> > > _singularity exec deepmosaic_v1.1.1.sif deepmosaic-draw -i variant_calling/software/annovar/input.txt -o /variant_calling/output_v2Filter/variants/deepmosaic -a /variant_calling/software/annovar/annovar -b hg38 -db gnomad_genome_
> > 
> > 
> > **Hi Rezwanuzzaman, did you check if the input file is tab delineated?**
> 
> Yes, I use tab delineated input file but the error is same 'Please provide a valid input file.'

Maybe try to remove the "chr" in your input?
